services:
  app1:
    image: ghcr.io/joojf/rinha-de-backend:latest
    environment:
      - BIND_ADDR=0.0.0.0:9999
      - DEFAULT_URL=http://payment-processor-default:8080
      - REDIS_URL=redis://redis:6379
      - REQ_TIMEOUT_MS=80
      - WORKERS=64
      - BATCH_SIZE=256
      - BATCH_FLUSH_MS=1
    depends_on:
      - redis
    networks:
      - default
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.60"
          memory: "110MB"

  app2:
    image: ghcr.io/joojf/rinha-de-backend:latest
    environment:
      - BIND_ADDR=0.0.0.0:9999
      - DEFAULT_URL=http://payment-processor-default:8080
      - REDIS_URL=redis://redis:6379
      - REQ_TIMEOUT_MS=80
      - WORKERS=64
      - BATCH_SIZE=256
      - BATCH_FLUSH_MS=1
    depends_on:
      - redis
    networks:
      - default
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.60"
          memory: "110MB"

  nginx:
    image: nginx:1.29-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2
    ports:
      - "9999:9999"
    networks:
      - default
    deploy:
      resources:
        limits:
          cpus: "0.05"
          memory: "30MB"

  redis:
    image: redis:7.2-alpine
    command: ["redis-server", "--appendonly", "no", "--maxmemory-policy", "allkeys-lru", "--tcp-keepalive", "60"]
    networks:
      - default
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "100MB"

networks:
  default:
    driver: bridge
  payment-processor:
    external: true
