name: publish-ghcr

on:
  push:
    branches: [ main ]
    paths:
      - Cargo.toml
      - Dockerfile
    tags:
      - 'v*'

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compute version/publish condition
        id: meta
        run: |
          set -euo pipefail
          if [ "${{ github.ref_type }}" = "tag" ]; then
            RAW="${{ github.ref_name }}"; VERS="${RAW#v}"; PUB=true
          else
            BEFORE="${{ github.event.before }}"
            VERS=$(sed -n 's/^version\s*=\s*"\([^"]\+\)"/\1/p' Cargo.toml | head -n1)
            if git show "$BEFORE":Cargo.toml >/tmp/old.toml 2>/dev/null; then
              OLD=$(sed -n 's/^version\s*=\s*"\([^"]\+\)"/\1/p' /tmp/old.toml | head -n1)
            else
              OLD=""
            fi
            parse() { IFS='.' read -r A B C <<< "$1"; echo "${A:-0} ${B:-0} ${C:-0}"; }
            if [ -z "$OLD" ]; then PUB=true; else
              read OA OB OC < <(parse "$OLD"); read NA NB NC < <(parse "$VERS")
              if [ "$NA" -gt "$OA" ] || { [ "$NA" -eq "$OA" ] && [ "$NB" -gt "$OB" ]; } || { [ "$NA" -eq "$OA" ] && [ "$NB" -eq "$OB" ] && [ "$NC" -gt "$OC" ]; }; then
                PUB=true
              else PUB=false; fi
            fi
          fi
          echo "version=$VERS" >> $GITHUB_OUTPUT
          echo "publish=$PUB" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        if: steps.meta.outputs.publish == 'true'
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        if: steps.meta.outputs.publish == 'true'
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        if: steps.meta.outputs.publish == 'true'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push (multi-arch)
        if: steps.meta.outputs.publish == 'true'
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/joojf/rinha-de-backend:${{ steps.meta.outputs.version }}
            ghcr.io/joojf/rinha-de-backend:latest
          labels: |
            org.opencontainers.image.source=${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.title=rinha-de-backend
