name: publish-ghcr

on:
  push:
    branches: [ main ]
    paths:
      - Cargo.toml
      - Dockerfile

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Detect version increase
        id: calc
        run: |
          set -euo pipefail
          BEFORE="${{ github.event.before }}"
          NEW_VERSION=$(sed -n 's/^version\s*=\s*"\([^"]\+\)"/\1/p' Cargo.toml | head -n1)
          if git show "$BEFORE":Cargo.toml >/tmp/old.toml 2>/dev/null; then
            OLD_VERSION=$(sed -n 's/^version\s*=\s*"\([^"]\+\)"/\1/p' /tmp/old.toml | head -n1)
          else
            OLD_VERSION=""
          fi
          parse() {
            IFS='.' read -r MA MI PA <<< "$1"; MA=${MA:-0}; MI=${MI:-0}; PA=${PA:-0}; echo "$MA $MI $PA";
          }
          if [ -z "$OLD_VERSION" ]; then
            INCREASED=true
          else
            read OMA OMI OPA < <(parse "$OLD_VERSION")
            read NMA NMI NPA < <(parse "$NEW_VERSION")
            if [ "$NMA" -gt "$OMA" ] || { [ "$NMA" -eq "$OMA" ] && [ "$NMI" -gt "$OMI" ]; } || { [ "$NMA" -eq "$OMA" ] && [ "$NMI" -eq "$OMI" ] && [ "$NPA" -gt "$OPA" ]; }; then
              INCREASED=true
            else
              INCREASED=false
            fi
          fi
          echo "version=$NEW_VERSION" >> $GITHUB_OUTPUT
          echo "version_increased=$INCREASED" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        if: steps.calc.outputs.version_increased == 'true'
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        if: steps.calc.outputs.version_increased == 'true'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push (linux/amd64)
        if: steps.calc.outputs.version_increased == 'true'
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64
          tags: |
            ghcr.io/joojf/rinha-de-backend:${{ steps.calc.outputs.version }}
            ghcr.io/joojf/rinha-de-backend:latest
          labels: |
            org.opencontainers.image.source=${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.title=rinha-de-backend
